version: '3.8'

services:
  # Spring MVC Application
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring-network
    restart: unless-stopped
    depends_on:
      - postgres

  # PostgreSQL Database
  postgres:
    image: postgres:14
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=springdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - spring-network
    restart: unless-stopped

networks:
  spring-network:
    driver: bridge

volumes:
  postgres-data:
